### ISSUE TITLE
Cannot connect to shelly api

### ISSUE THREAD

**Issue by t0mm96** [aexel90/shelly_exporter#1]
Hi.

When I try to run the script it only gives me the following:

Error:  Response not OK: 400 Bad Request
Metric: shelly_ht_info
 - Exporter Result:
 -  Metric: shelly_ht_temperature
  - Exporter Result:
  -  Metric: shelly_ht_humidity
  - Exporter Result:

The command I use is this: /home/ikt/go/bin/shelly_exporter -metrics-file /home/ikt/go/bin/shelly-metrics.json -test

shelly-metrics.json is filled in with the correct url, auth key and device id

When I use the same device id, auth key and url in the following curl command, it works:
curl -X POST https://shelly-38-eu.shelly.cloud/device/status -d "id=XXXXXX&auth_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

Any idea what might be wrong?

**Comment by aexel90** [comment]
hi,

It seems that your "shelly-metrics.json" file is not correct. Please check id and auth key. 
"account":{
        "auth_key": "<your_key>",
        "url": "shelly-38-eu.shelly.cloud"
    },
...

Also start with having only on device in json and test!

Regards,
Alex

**Comment by t0mm96** [comment]
Hi and thanks for your reply :)

I have double and triple checked, but as far as I can se, both my auth key and device id is correct, but I still get the same error.

I put my shelly-metrics file in pastebin with the authkey and deviceid removed  https://pastebin.com/9qpaGJb0

Regards
T

**Comment by t0mm96** [comment]
Hi and thanks for your reply :)

I have double and triple checked, but as far as I can se, both my auth key and device id is correct, but I still get the same error.

I put my shelly-metrics file in pastebin with the authkey and deviceid removed  https://pastebin.com/xqys4j1v

Regards
T

**Comment by aexel90** [comment]
Hi,

you still have roller devices (maybe from the example) inlucded.
This should be your correct json: https://pastebin.com/Tg3tS6Ht

Regards,
Alex

**Comment by t0mm96** [comment]
Thank you, that did the trick.
