### ISSUE TITLE
Nix package

### ISSUE THREAD

**Issue by drupol** [aexel90/shelly_exporter#2]
Hello,

I would like to monitor my shellys and it seems your package might be a good fit for my router.
As I'm using NixOS, I would like to use this package and let the community enjoy it as well.

I'm planning to create a pull-request to submit your software to Nix.
However, it would be super nice if you could make a tag, it would be easier for me for the submission process.

Do you think you can make a tag?

**Comment by drupol** [comment]
Closing the issue since I got not feedback.

**Comment by aexel90** [comment]
Sorry, didn`t notice it before.
Successfully tagged.

**Comment by drupol** [comment]
Oh thanks! I'll keep you updated of the progress.

**Comment by drupol** [comment]
Pull request created: https://github.com/NixOS/nixpkgs/pull/213534
